import { type Metadata } from 'next'
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from '@clerk/nextjs'
import { Geist, Geist_Mono } from 'next/font/google'
import localFont from 'next/font/local'
import './globals.css'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

const editorialNew = localFont({
  src: [
    {
      path: '../public/fonts/PPEditorialNew-Variable.ttf',
      style: 'normal',
    },
    {
      path: '../public/fonts/PPEditorialNew-ItalicVariable.ttf',
      style: 'italic',
    },
  ],
  variable: '--font-editorial-new',
  display: 'swap',
})

export const metadata: Metadata = {
  title: 'Clerk Next.js Quickstart',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable} ${editorialNew.variable} antialiased`}>
          {children}
        </body>
      </html>
    </ClerkProvider>
  )
}